In [1]:
import numpy as np

In [2]:
l_1 = [1,2,3,4]

In [4]:
array_1 = np.array(l_1)

In [5]:
l_2 = [11,12,13,14]

In [6]:
array_2 = np.array(l_2)

In [7]:
array = [array_1, array_2]

In [8]:
array

[array([1, 2, 3, 4]), array([11, 12, 13, 14])]

In [9]:
m_array = np.array(array)

In [10]:
m_array

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [12]:
m_array.shape

(2, 4)

In [13]:
m_array.dtype

dtype('int64')

In [14]:
zeros_5 = np.zeros(5)

In [15]:
zeros_5

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
ones_5 = np.ones([5,5])

In [17]:
ones_5

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
empty_5 = np.empty(5)

In [19]:
empty_5

array([  0.00000000e+000,   1.28822983e-231,   1.32786634e-315,
        -3.10503637e+231,  -2.68156175e+154])

In [20]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [24]:
5/2

2.5

In [26]:
matrix = np.array([[1,2,3,4],[7,8,9,10]])

In [27]:
matrix

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [28]:
matrix*matrix

array([[  1,   4,   9,  16],
       [ 49,  64,  81, 100]])

In [29]:
matrix*matrix - matrix

array([[ 0,  2,  6, 12],
       [42, 56, 72, 90]])

In [30]:
1/matrix

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.14285714,  0.125     ,  0.11111111,  0.1       ]])

In [31]:
array_ex = np.arange(0,11)

In [32]:
array_ex[5]

5

In [33]:
array_ex[0:5]

array([0, 1, 2, 3, 4])

In [35]:
array_ex[0:5] = [4,3,2,1,0]

In [36]:
array_ex

array([ 4,  3,  2,  1,  0,  5,  6,  7,  8,  9, 10])

In [37]:
array_ex[0:5] = 0

In [38]:
array_ex

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [39]:
array_ex = np.arange(0,11)

In [40]:
array_ex

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
slice_ex = array_ex[0:6]

In [42]:
slice_ex[:] = 0

In [44]:
slice_ex

array([0, 0, 0, 0, 0, 0])

In [46]:
array_ex

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [47]:
array_copy = array_ex.copy()

In [48]:
array_copy 

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [49]:
array_ex[0:6] = [0,1,2,3,4,5]

In [51]:
array_3d = np.array(([5,10,15],[3,2,1],[20,21,22]))

In [52]:
array_3d

array([[ 5, 10, 15],
       [ 3,  2,  1],
       [20, 21, 22]])

In [53]:
array_3d[1]

array([3, 2, 1])

array(rows, collums)

In [55]:
array_3d[:2,1:]

array([[10, 15],
       [ 2,  1]])

In [60]:
arr_zeros = np.zeros((10,10))

In [61]:
arr_zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [63]:
arr_zeros.shape[1]

10

In [70]:
for i in range(arr_zeros.shape[1]):
    arr_zeros[i]=i

In [71]:
arr_zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [73]:
arr_zeros[[2,5,3,7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [75]:
array_50 = np.arange(50).reshape(10,5)

In [76]:
array_50

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [77]:
array_50.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [78]:
np.dot(array_50.T, array_50)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [79]:
array3D = np.arange(50).reshape(5,5,2)

In [80]:
array3D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [81]:
array3D.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [92]:
simple_arr = np.array([[1,2,3]])

In [93]:
simple_arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])